In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3], dtype=np.int32)
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [19]:
#get dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#set shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#get type
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
#get itemsize
a.itemsize

#this will 4 because it is 32bit integer

4

In [13]:
b.itemsize

#and this is 64bit integer

8

In [14]:
#get total no of elements
a.size

3

In [15]:
b.size

6

In [16]:
#get total size
a.nbytes

12

In [17]:
a.itemsize*a.size

12

In [18]:
b.nbytes

48