In [21]:
import numpy as np

Basics

In [22]:
a = np.array([1,2,3], dtype=np.int32)
print(a)

[1 2 3]


In [23]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [24]:
#get dimension
a.ndim

1

In [25]:
b.ndim

2

In [26]:
#set shape
a.shape

(3,)

In [27]:
b.shape

(2, 3)

In [28]:
#get type
a.dtype

dtype('int32')

In [29]:
b.dtype

dtype('float64')

In [30]:
#get itemsize
a.itemsize

#this will 4 because it is 32bit integer

4

In [31]:
b.itemsize

#and this is 64bit integer

8

In [32]:
#get total no of elements
a.size

3

In [33]:
b.size

6

In [34]:
#get total size
a.nbytes

12

In [35]:
a.itemsize*a.size

12

In [36]:
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [38]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
#get a specific element [r,c]
A[1,5]

np.int64(13)

In [40]:
#get a specific row
A[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
#get a specific column
A[:, 2]

array([ 3, 10])

In [47]:
#getting a little more fancy [startindex:endindex:stepsize]
A[0, 2:6:3]  

array([3, 6])